### ISSUE TITLE
ci(myjobhunter): frontend-build + Stack smoke fail with rollup/rolldown PluginContextMeta type mismatch

### ISSUE THREAD

**Issue by jykwon91** [jykwon91/MyFreeApps#104]
## Symptom

`frontend-build / myjobhunter` and `Stack smoke (compose up + health + login)` fail building `apps/myjobhunter/frontend` with:

```
vitest.config.ts(11,13): error TS2769: No overload matches this call.
  Property 'rolldownVersion' is missing in type 'PluginContextMeta' (rollup) but required in type 'PluginContextMeta' (rolldown).
```

`tsc -b && vite build` fails with exit code 2.

## Status

Pre-existing — root cause is a type-version drift in `node_modules` between the `rollup` and `rolldown` packages co-installed via Vite/Vitest plugins. Not introduced by #102.

## Fix sketch

One of:
- Pin `rollup` and `rolldown-vite` to compatible versions in `apps/myjobhunter/frontend/package.json` (or root `package.json`'s overrides)
- Cast the plugin in `vitest.config.ts` to bypass the type incompatibility (last-resort workaround)
- Bump `vitest` and `@vitejs/plugin-react` to versions whose plugin author signature matches the installed rollup major

## Workaround

Admin-merge of #102 documents this as accepted-risk so the rest of the monorepo's CI can run.

**Comment by jykwon91** [comment]
Closing as stale. PR #435 (merged today) ran `frontend-build / myjobhunter` and it passed. The rollup/rolldown type mismatch must have resolved via a dep bump in one of the chore branches. Reopen if it resurfaces.
